### ISSUE TITLE
Most of the schematic is not getting rendered on the site.

### ISSUE THREAD

**Issue by imrishabh18** [tscircuit/schematic-viewer#40]
https://schematic-viewer.vercel.app/ Most of the components are not getting rendered, seems like something is broken.

**Comment by seveibar** [comment]
I suspect it's because of this: https://github.com/tscircuit/schematic-viewer/commit/095e3b4a8bfa1bfe0a028a3c53f3dd62a7201c78

I had a similar issue in another repo where it has to do with the builder using new functions from `@tscircuit/soup-util`, fix is probably to upgrade that dep

In the future we should have visual regression testing (storybook offers this as a service- i'll look into it)

**Comment by seveibar** [comment]
#41 should fix this
